version: '2'
services:
  postgresql:
    image: postgres:9.5
    restart: always
    env_file: docker-compose.env
    #volumes:
    #  - ./data/postgres:/var/lib/postgresql/data

  web_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    links:
      - postgresql
      - elastic
    #volumes:
    #  - ./data/ucrm:/data
    ports:
      - 8080:80
      - 8081:81
      - 8443:443
    command: "server"

  elastic:
    image: elasticsearch:2
    restart: always

  sync_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    #volumes:
    #  - ./data/ucrm:/data
    links:
      - postgresql
    command: "sync"

  crm_invoice_send_email_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    #volumes:
    #  - ./data/ucrm:/data
    links:
      - postgresql
    command: "crm_invoice_send_email"

  crm_draft_approve_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    #volumes:
    #  - ./data/ucrm:/data
    links:
      - postgresql
    command: "crm_draft_approve"

  crm_search_devices_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    #volumes:
    #  - ./data/ucrm:/data
    links:
      - postgresql
    command: "crm_search_devices"
